spring:
  profiles:
    active: dev
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/netic
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  eureka:
#    instance:
#      hostname: peer1
#    client:
#      serviceUrl:
  #      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/
