spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    sql-script-encoding: utf-8
    url: jdbc:mysql://localhost:3306/netic?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root
  jpa:
    #默认使用InnoDB引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true








