server:
  port: 7070
  context-path: /rays
spring:
  profiles:
    active: dev
  jpa:
    #默认使用InnoDB引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect




  #  eureka:
  #    instance:
  #      hostname: peer1
  #    client:
  #      serviceUrl:
  #      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/